### ISSUE TITLE
contribute mapping quality ideas? 

### ISSUE THREAD

**Issue by colindaven** [gui11aume/smmfdp#10]
Hi,

interesting approach and much needed, as accurate mapping quality is critical for short reads.

I wonder if it makes sense to further develop your own aligner to compete with the 200+ aligners already out there, or to contribute (if possible) your MQ ideas to a big, famous new project such as bwa-mem2. 

Just my 2 cents, I'm trying your aligner now anyway and can at least reference my unusual metagenomic reference genomes so far.

cheers,
Colin

**Comment by gui11aume** [comment]
Dear Colin,

Thanks for your input and thanks for using mmp.

I am with you on this one. This mapper is rather for "inspirational purposes" and I hope that Heng Li (@lh3) would be interested in incorporating some of our features (perhaps with us on board). However, this is not up to us... For now the best we can do is test whether the approach works in practice and contact the authors of the mainstream mappers if this is the case. That has always been the plan.

I have to admit that I was not aware of the bwa-mem2 project. If you are in contact with them I'd love to be introduced so that we can discuss possible improvements. It seems that the aim is to produce exactly the same output as bwa-mem so I am not sure they will be interested, but you never know.

PS: and of course we are more than happy to receive your feedback on the software and to help you use it if there is any issues (we've been fixing bugs on a daily basis recently so we apologize to those who may have had a frustrating experience).

**Comment by colindaven** [comment]
Hey, I don't know the guys behind from intel behind the bwa-mem2 project, but you could just outline your interest and code and ask if they'd be happy for contributions in the form of PRs etc. 

For me as a user/bioinformatician it's quite difficult to find the time to assess the accuracy of MQ across various tools, since my users judge me on my ability to run current pipelines across a wide variety of omics. Having said that, as a metagenomics pipeline developer and user MQ is absolutely key to using short reads in metagenomics.
