### ISSUE TITLE
Paired-end reads mapping 

### ISSUE THREAD

**Issue by AdrienOliva** [gui11aume/smmfdp#13]
Hi,

Does  MMP support and can use paired-end reads ?
As I couldn't find the information anywhere I tried : `mmp REF R1.fq R2.fq > out.sam` but got the "too many arguments" errors. 

Thanks,
Adrien

**Comment by gui11aume** [comment]
Hi @AdrienOliva,

MMP does not support paired-end reads. The main reason is that the mapping quality (MAPQ field) of paired-end reads depends on the application, so we would need to make different models for every case. For instance, if the reads are from genomic DNA, it is expected that they map close to each other so the MAPQ of a pair mapping to different chromosomes would be low. In contrast, for a Hi-C experiment, the same pair could have a high MAPQ because the ends can map to different chromosomes.

MMP does not split the reads, and it outputs them in the same order as the input FASTQ files. So if you map the two files separately, they are fairly easy to join, even though I understand that this is perhaps not what you want.

I am sorry that we don't really address your issue. If you have a good idea of how this could be addressed in a general way, we'll do our best to implement it.

**Comment by AdrienOliva** [comment]
Thanks a lot for your answer, I wasn't aware of that behaviour of MMP.  That does answer my question and I will probably use your suggested idea to treat my dataset.
